### ISSUE TITLE
Any chance we get Darktide source code?

### ISSUE THREAD

**Issue by igromanru** [Aussiemon/Vermintide-2-Source-Code#3]
Hello, first of all I really appreciate your work. Having all the Lua source code is immensely helpful.  
Are you planning to do the same for Warhammer 40k: Darktide, which is based on the same engine?  
I know they haven't added modding support yet, but it would be really helpful to know how it works, especially since so many mechanics aren't explained by the game.

**Comment by Aussiemon** [comment]
Sent you an email

**Comment by Catpuccino6142** [comment]
I would love to learn the new mechanics from Darktide. Any chance you share the Darktide source code in the future?

**Comment by Aussiemon** [comment]
For posterity, Darktide's Lua sources are now publicly visible: <https://github.com/Aussiemon/Darktide-Source-Code>
